### ISSUE TITLE
Attribute used in an CPP property is disallowed in attribute resolving callstack of command handlers

### ISSUE THREAD

**Issue by tandev** [ecotoneframework/ecotone-dev#336]
**Ecotone version(s) affected**: 1.224.0

**Description**  

The following issue occurs on warmup, when using an Attribute which should be allowed in this place in CPP

`Uncaught Error: Attribute "Symfony\Component\DependencyInjection\Attribute\AutowireLocator" cannot target property (allowed targets: parameter)`

This attribute(Symfony\Component\DependencyInjection\Attribute\AutowireLocator) for example is allowed by symfony to be used for properties in a CPP definition

```php
 public function __construct(
        #[AutowireLocator(FooLocatedService::class)]
        private ContainerInterface $foos,
    ) {
    }
```

So i think this should be allowed by ecotone too

**How to reproduce**  
I set an example symfony application with ecotone integration where this can reproduced at cache warmup
https://github.com/tandev/ecotone-attribute-resolving/tree/main

**Comment by dgafka** [comment]
Hey @tandev,

This bug comes from how attribute is defined:
![image](https://github.com/user-attachments/assets/fa646cbb-7cd2-43de-ad65-092e079565e8)

Where in your usage, you're using promoted properties, therefore to allow for such usage, it should be done like this to be correct:
![image](https://github.com/user-attachments/assets/4003dcbc-b7ba-46cb-a850-34f8cd6dc55e)

Ecotone does do nothing magically here, it just initializes this Attribute, where it's not possible due to incorrect definition.  
I am not sure, how does it work on the Symfony side thought. Maybe they do not initialize it at all?

**Comment by jlabedo** [comment]
@dgafka , it is because of a promoted property (a parameter that is also a property). I am working on a fix

**Comment by dgafka** [comment]
@jlabedo ah I see. 
Maybe we intitialize it in context of property (ClassDefinition)? If so, we could check if this Attribute has `TARGET_PROPERTY` option, and only then add initialize and add it?

**Comment by jlabedo** [comment]
I tried `if ($attribute->getTarget() & \Attribute::TARGET_PROPERTY)` but the target is always property (even if not an allowed target)
Maybe we could use reflection on the attribute itself to get its class "\Attribute" attribute... and then get its targets. But seems a bit tool complicated instead of a documented try catch...

**Comment by dgafka** [comment]
Hmm, as long as we can catch this specific error, that should also do a trick, and will be less time consuming process than check of each attribute
