### ISSUE TITLE
How to use #[QueryHandler]

### ISSUE THREAD

**Issue by galliroberto** [ecotoneframework/ecotone-dev#379]
**Ecotone version(s) affected**: 1.231.0
**Symfony version**: 6.4.11

**Description**  
I want to send query **FindCompanyCollectionQuery** throw **queryBus** and use **queryHandler** to handle it.

I get the error
```
Can't send query to Organization\\Modules\\Company\\Domain\\Query\\FindCompanyCollectionQuery. No Query Handler defined for it. Have you forgot to add #[QueryHandler] to method?
```

I also tried with **sendWithRouting**

I get the error:
```
Can't send query to customRoute. No Query Handler defined for it. Have you forgot to add #[QueryHandler] to method?
```

I also tried with commandBus and  #[CommandHandler] and get the error that route is not defined.

**Context**  
![image](https://github.com/user-attachments/assets/27b150d2-882c-454f-a6f5-3f171bcc1b24)

![image](https://github.com/user-attachments/assets/2e5f379e-2fbf-4878-ae17-1d53b3f4172b)

**Comment by jlabedo** [comment]
Hello @galliroberto , I think it is because of a misconfiguration. I supposed from your screenshots that you are using Ecotone with Symfony, and that your source code is under an "Organization" namespace (not the default "App" namespace).

By default, Ecotone looks for attributes in the "App" namespace and the "src" directory. If you have a different setup, you should add the `namespaces` configuration in Symfony (see: https://docs.ecotone.tech/modules/symfony/symfony-ddd-cqrs-event-sourcing#namespaces)

Something like this in `config/packages/ecotone.yaml`:
```yaml
ecotone: 
    namespaces: ["Organization"]
```

**Comment by galliroberto** [comment]
Thank you so much.
You are really helpful
